# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('writer', models.CharField(max_length=50, verbose_name='作者')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='修改日期')),
                ('content', models.TextField()),
                ('is_show', models.BooleanField()),
            ],
            options={
                'db_table': 'Article',
            },
        ),
    ]
